/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search published hotels
         * @description Only PUBLISHED hotels are ever returned — the filter is in SQL, so a non-published row cannot leak through a page boundary. Prices are the cheapest room that fits `guests`, in the requested currency. Dates are accepted and validated here; availability filtering lands with the quote endpoint in T18.
         */
        get: operations["HotelsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hotel detail
         * @description Resolves by uuid or by slug — the frontend links to `/hotels/{slug}`. A hotel that is not PUBLISHED is a 404 for everyone but its own host, so the endpoint cannot be used to discover a draft listing.
         */
        get: operations["HotelsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and database reachability
         * @description Always 200. `status` is "ok" only when the database answered; `db` carries reachability on its own, so a monitor can alert on it without parsing a status string.
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
        AmenitySlug: string;
        HotelImage: {
            url: string;
            altText: string | null;
            aspect: string;
            width: number;
            height: number;
        };
        Money: {
            amountCents: number;
            /** @description ISO 4217 code. */
            currency: string;
        };
        RatingSummary: {
            average: number | null;
            totalReviews: number;
        };
        HotelCard: {
            /** Format: uuid */
            id: string;
            /** @description Stable, URL-safe. The detail route accepts this. */
            slug: string;
            name: string;
            city: string;
            country: string;
            starRating: number;
            coverImage: components["schemas"]["HotelImage"] | null;
            amenityIds: components["schemas"]["AmenitySlug"][];
            rating: components["schemas"]["RatingSummary"];
            priceFrom: components["schemas"]["Money"] | null;
            /** @description ISO 4217 code the prices are quoted in. */
            currency: string;
        };
        HotelRoom: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            bedType: string;
            maxGuests: number;
            totalInventory: number;
            price: components["schemas"]["Money"] | null;
            images: components["schemas"]["HotelImage"][];
        };
        HotelDetail: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string;
            addressLine: string;
            city: string;
            country: string;
            lat: number;
            lng: number;
            starRating: number;
            /** @enum {string} */
            status: "PENDING" | "PUBLISHED" | "REJECTED" | "SUSPENDED";
            /** @description Local wall-clock `HH:mm`. */
            checkInTime: string;
            /** @description Local wall-clock `HH:mm`. */
            checkOutTime: string;
            currency: string;
            coverImage: components["schemas"]["HotelImage"] | null;
            /** @description Hotel-level imagery, cover first. */
            images: components["schemas"]["HotelImage"][];
            amenityIds: components["schemas"]["AmenitySlug"][];
            rating: components["schemas"]["RatingSummary"];
            rooms: components["schemas"]["HotelRoom"][];
            host: {
                /** Format: uuid */
                id: string;
                name: string;
            } | null;
        };
        HotelListData: {
            items: components["schemas"]["HotelCard"][];
            /** @description Total matching hotels, ignoring pagination. */
            total: number;
            page: number;
            pageSize: number;
        };
        HealthData: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            db: "up" | "down";
        };
        HotelListEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["HotelListData"];
        };
        HotelDetailEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["HotelDetail"];
        };
        HealthEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["HealthData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HotelsController_findAll: {
        parameters: {
            query?: {
                /** @description City name, case-insensitive exact match. Omit to search every city. */
                city?: string;
                /** @description First night, `YYYY-MM-DD`. Stored as a Postgres DATE, never a timestamp. */
                checkIn?: string;
                /** @description Last day the guest leaves, `YYYY-MM-DD`. Must be strictly after `checkIn`. The stay is half-open, so a checkout equal to another booking check-in never overlaps. */
                checkOut?: string;
                /** @description Party size, 1-20. A hotel qualifies only if it has a room that fits. */
                guests?: number;
                /** @description LOWEST nightly price in MAJOR currency units, not cents. `150` means 150.00. Must be <= maxPrice. */
                minPrice?: number;
                /** @description Highest nightly price in MAJOR currency units, not cents. */
                maxPrice?: number;
                /** @description Comma-separated amenity slugs, ANDed: `wifi,pool` returns only hotels with both. Slugs are lowercase: wifi, pool, breakfast, pets, ac, workspace, gym, spa, restaurant, bar, parking, shuttle. */
                amenities?: string;
                /** @description `recommended` (default) is star rating then name. `rating_desc` puts hotels with no reviews last, because a null average is not the best rating. */
                sort?: "recommended" | "price_asc" | "price_desc" | "rating_desc" | "name_asc";
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page, 1-50. */
                pageSize?: number;
                /** @description ISO 4217 code to price in. Only USD has price rows today; a currency with no `room_prices` row yields `priceFrom: null`, never zero. */
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of hotels. `items` is empty and `total` is 0 when nothing matches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelListEnvelope"];
                };
            };
            /** @description The query string failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    HotelsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The hotel, with rooms, amenities, images and a review summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelDetailEnvelope"];
                };
            };
            /** @description No such hotel, or it is not visible to this caller. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service answered. The database may still be down — read `db`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
}
